# Generated by Django 5.0.6 on 2024-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('summery', models.TextField(max_length=10000)),
                ('skills', models.TextField(max_length=10000)),
                ('experience', models.TextField(max_length=10000)),
                ('education', models.TextField(max_length=10000)),
            ],
        ),
    ]
